# Generated by Django 5.0.3 on 2024-04-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0004_presentmeeting_allowed_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentmeeting',
            name='allowed_participants',
        ),
        migrations.AddField(
            model_name='presentmeeting',
            name='allowed_participants',
            field=models.TextField(default='[]'),
        ),
    ]
