# Generated by Django 5.0.3 on 2024-04-04 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0005_remove_presentmeeting_allowed_participants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentmeeting',
            name='allowed_participants',
        ),
    ]
