# Generated by Django 5.0.3 on 2024-04-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0008_presentmeeting_join_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentmeeting',
            name='durations',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='presentmeeting',
            name='leave_times',
            field=models.JSONField(default=dict),
        ),
    ]
