# Generated by Django 5.0.3 on 2024-04-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0009_presentmeeting_durations_presentmeeting_leave_times'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presentmeeting',
            old_name='durations',
            new_name='interval',
        ),
    ]
