# Generated by Django 5.0.3 on 2024-04-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0011_sectiondetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentmeeting',
            name='secname',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
